export const FLIRTY_QUOTES = [
  "Mirror mirror on the wall, who’s the hottest of them all? (Shreya, obviously) 💋",
  "Certified 10/10 with an attitude that slays 🔥",
  "Too glam to give a damn, too gorgeous to ignore 💅",
  "Heaven called, they're looking for their most dangerous angel 😇✨",
  "Is it getting hot in here or is it just this gallery? 🥵🌶️",
  "Dangerous curves ahead... handle with pure adoration 💖",
  "Beauty, brains, and the perfect amount of mischief 😈",
  "Looking this fine should honestly come with a warning label ⚠️🍓",
  "Sugar, spice, and everything dangerously nice 🎀",
  "Living rent-free in everyone's head since day one 👑",
  "Pure magnificence wrapped in pink satin 🌸",
  "A little sweet, a little wild, and completely unforgettable 💫",
  "Main character energy only ✨💅",
  "Serving looks, breaking hearts, and taking names 💌",
  "A work of art in a world full of sketches 🎨💖",
  "Too fine to be real, yet here she is 🔥",
  "The definition of perfection with a side of sass 💋",
  "She’s got that whole daydream-wrapped-in-fire thing going on 🌙🔥",
  "Flawless from every angle, undeniable in every way 💎",
  "Goddess behavior: 100% unlocked 👑",
  "Sweet as candy with an intoxicating edge 🍭",
  "Effortlessly breathtaking every single second 🌹",
  "Walks like a boss, shines like a diamond 💎✨",
  "Catch flights, break hearts, stay gorgeous ✈️💖",
  "She’s not just a vibe, she’s the whole soundtrack 🎶",
  "Spicy enough to burn, sweet enough to crave 🌶️🍯",
  "Elegance with a hint of wild ambition 🐆",
  "Radiating pure royalty in soft pastel pink 👸🎀",
  "Too cute to care, too hot to handle 💖",
  "Every photo is a masterclass in magnificence 📸💋",
  "Unapologetically sassy, effortlessly iconic ✨",
  "That smile could start a revolution (or stop traffic) 😉",
  "Eyes that captivate, presence that commands 👁️💫",
  "A masterpiece that needs no filter 🖼️🌸",
  "A whole entire mood, 24/7/365 🔥"
];
